var movies = [
    "Taxi Driver",
    "Apocalypto",
    "The Shawshank Redemption",
    "American Pie",
    "Saving Private Ryan",
    "Step Brothers",
    "Fight Club",
    "The Hangover",
    "Easy A",
    "Wedding Crashers",
    "Borat",
    "The 40 Year Old Virgin",
    "Groundhog Day",
    "The Dark Knight",
    "The Green Mile",
    "The Way of The Gun",
    "Friday",
    "Do the Right Thing",
    "The Basketball Diaries",
    "The Longest Yard",
    "There Will Be Blood",
    "Django Unchained",
    "Pulp Fiction",
    "21 Jump Street",
    "The Terminator",
    "Looper",
    "Se7en",
    "Reservoir Dogs",
    "Napoleon Dynamite",
    "The Royal Tenenbaums",
    "Rushmore",
    "The Darjeeling Limited",
    "Fantastic Mr. Fox",
    "Magnolia",
    "The Master",
    "Fargo",
    "Full Metal Jacket",
    "Grand Budapest Hotel",
    "Training Day",
    "Remember the Titans",
    "Harold and Kumar Go To White Castle",
    "Star Trek",
    "No Country for Old Men",
    "Donnie Darko",
    "Psycho",
    "Misery",
    "Office Space",
    "Horrible Bosses",
    "Inglorious Basterds",
    "300",
    "Clerks",
    "Mallrats",
    "Chasing Amy",
    "Dogma",
    "The Fellowship of the Ring",
    "The Two Towers",
    "The Return of the King",
    "The Silence of the Lambs",
    "The Shining",
    "The Conjuring",
    "The Sixth Sense",
    "Dodgeball: A True Underdog Story",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Deathly Hallows",
    "Batman Begins",
    "The Dark Knight Rises",
    "American Beauty",
    "The Graduate",
    "10 Things I Hate About You",
    "Knocked Up",
    "A Clockwork Orange",
    "Old School",
    "Fast Times at Ridgemont High",
    "Crazy, Stupid, Love",
    "Role Models"



    



]

var shows = [
    "The Wire",
    "Breaking Bad",
    "It's Always Sunny in Philadelphia",
    "Invincible",
    "The Boys",
    "Avatar: The Last Airbender",
    "The Legend of Korra",
    "Dragon Ball",
    "Dragon Ball Z",
    "Dragonball Super",
    "Bleach",
    "Shameless",
    "Black Mirror",
    "Better Call Saul",
    "Stranger Things",
    "The Queen's Gambit",
    "Ozark",
    "The Witcher",
    "Outer Banks",
    "Peaky Blinders",
    "Arcane",
    "Futurama",
    "Rick and Morty",
    "Archer",
    "Family Guy",
    "The Eric Andre Show",
    "Everybody Hates Chris",
    "Modern Family",
    "Ned's Declassified",
    "Spongebob Squarepants",
    "Blue Mountain State",
    "Daria",
    "Squid Game",
    "One on One",
    "As Told By Ginger",
    "The Sopranos",
    "Narcos",
    "Narcos: Mexico",
    "Zoey 101",
    "The Good Place",
    "Abbott Elementary",
    "Boardwalk Empire",
    "Brooklyn Nine Nine",
    "Deadwood",
    "New Girl",
    "Power",
    "Pretty Little Liars",




]

function getMovie(){
    var randomMovieNumber = Math.floor(Math.random() * movies.length)
    document.getElementById('newMovieSection').innerHTML = movies[randomMovieNumber];
}

function getShow(){
    var randomShowNumber = Math.floor(Math.random() * shows.length)
    document.getElementById('newShowSection').innerHTML = shows[randomShowNumber];
}